Spanish translation
toasterofbread/spmp pull request #139
Opened 2023-09-12 17:19 UTC by MRGABOZ

I'm not adding external strings correctly let me know if I should fix something

2023-09-13 22:09 UTC, toasterofbread requested changes
Just one thing to fix, looks good other than that!

2023-09-13 22:09 UTC, toasterofbread commented on shared/src/commonMain/kotlin/com/toasterofbread/spmp/resources/uilocalisation/localised/UILanguages.kt
> +    val es: String = "es-US
Missing closing quote

2023-09-13 22:51 UTC, MRGABOZ commented
Ok perfect, I think I already corrected it  :)

2023-09-14 13:10 UTC, merged

2023-09-14 13:11 UTC, toasterofbread commented
Thanks for the translation!